---
title: "subActPlots"
author: "AlistairGJ"
date: "14/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(ggplot2)
library(ggridges)
library(dplyr)
library(viridis)
library(lubridate)
library(ggExtra)
library(tidyr)
library(readr)
library(cowplot)
library(data.table)
library(ggsci)
```

dsPRE <- read_csv('/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/S1SubActivities_preprocessedWfeatures.csv', 

http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf

```{r}
library(readr)
files <- read_csv('/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/files.csv', 
    col_names = FALSE)
```

```{r}
best_feats <- dplyr::filter(files, grepl("best_feats", X1))
dt <- dplyr::filter(files, grepl("_dt", X1))
roc <- dplyr::filter(files, grepl("_roc", X1))
report <- dplyr::filter(files, grepl("_rep", X1))
confusion <- dplyr::filter(files, grepl("confusion", X1))
```




```{r}
library(tidyverse)
library(stringr)
list_of_files <- list.files(path = '/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/',
                            pattern = '_rep.csv',
                            full.names = TRUE)
df <- list_of_files %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x, col_types = cols(), col_names = FALSE), .id = "file_name")
```

```{r}
df$file_name <- gsub("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/", "", df$file_name)
df$file_name <- gsub("_rep.csv", "", df$file_name)
df$file_name <- substring(df$file_name, 2)
```

```{r}
df$X1 <- gsub("0.0", "0", df$X1)
df$X1 <- gsub("1.0", "1", df$X1)
colnames(df) <- c('fn','X1','precision','recall','f1score','support')
df$fn <-  paste(df$fn, df$X1, sep = "_")
df$fn <- gsub("macro avg", "m.avg", df$fn)
df$fn <- gsub("weighted avg", "w.avg", df$fn)
df <- na.omit(df)
#drops <- c("X1")
#df <- df[ , !(names(df) %in% drops)]
```

```{r}
df$precision <- as.numeric(as.character(df$precision))
df$precision <- format(round(df$precision, 3), nsmall = 3)
df$recall <- as.numeric(as.character(df$recall))
df$recall <- format(round(df$recall, 3), nsmall = 3)
df$f1score <- as.numeric(as.character(df$f1score))
df$f1score <- format(round(df$f1score, 3), nsmall = 3)
df$support <- as.numeric(as.character(df$support))
df$support <- format(round(df$support, 0), nsmall = 0)
```

```{r}
df_accuracy <- df[grepl("accuracy", df$fn),]
df_final <- df[!grepl("accuracy", df$fn),]
```

```{r}
drops <- c("recall", "f1score", "support")
df_accuracy <- df_accuracy[ , !(names(df_accuracy) %in% drops)]
colnames(df_accuracy)[3] <- "accuracy"
```

```{r}
colnames(df_final)[1] <- "subAct_metric"
colnames(df_final)[3] <- "precision_i"
colnames(df_final)[4] <- "recall_i"
colnames(df_final)[5] <- "f1score_i"
colnames(df_final)[6] <- "support_i"
colnames(df_accuracy)[1] <- "subAct_metric"
colnames(df_accuracy)[3] <- "accuracy_i"
```

```{r}
df_iAll <- df_final
df_iAcc <- df_accuracy 
```


```{r}
write.csv(df_final, file="/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/df_final.csv")
write.csv(df_accuracy, file="/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/df_accuracy.csv")
```

## Energy Only

```{r}
library(tidyverse)
library(stringr)
list_of_files <- list.files(path = '/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/energyOnly/',
                            pattern = '_rep.csv',
                            full.names = TRUE)
df <- list_of_files %>%
  setNames(nm = .) %>% 
  map_df(~read_csv(.x, col_types = cols(), col_names = FALSE), .id = "file_name")
```

```{r}
df$file_name <- gsub("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/energyOnly/", "", df$file_name)
df$file_name <- gsub("_rep.csv", "", df$file_name)
df$file_name <- substring(df$file_name, 2)
```

```{r}
df$X1 <- gsub("0.0", "0", df$X1)
df$X1 <- gsub("1.0", "1", df$X1)
colnames(df) <- c('fn','X1','precision','recall','f1score','support')
df$fn <-  paste(df$fn, df$X1, sep = "_")
df$fn <- gsub("macro avg", "m.avg", df$fn)
df$fn <- gsub("weighted avg", "w.avg", df$fn)
df <- na.omit(df)
```

```{r}
df$precision <- as.numeric(as.character(df$precision))
df$precision <- format(round(df$precision, 3), nsmall = 3)
df$recall <- as.numeric(as.character(df$recall))
df$recall <- format(round(df$recall, 3), nsmall = 3)
df$f1score <- as.numeric(as.character(df$f1score))
df$f1score <- format(round(df$f1score, 3), nsmall = 3)
df$support <- as.numeric(as.character(df$support))
df$support <- format(round(df$support, 0), nsmall = 0)
```

```{r}
df_accuracy <- df[grepl("accuracy", df$fn),]
df_final <- df[!grepl("accuracy", df$fn),]
```

```{r}
drops <- c("recall", "f1score", "support")
df_accuracy <- df_accuracy[ , !(names(df_accuracy) %in% drops)]
colnames(df_accuracy)[3] <- "accuracy"
```

```{r}
colnames(df_final)[1] <- "subAct_metric"
colnames(df_final)[3] <- "precision_ii"
colnames(df_final)[4] <- "recall_ii"
colnames(df_final)[5] <- "f1score_ii"
colnames(df_final)[6] <- "support_ii"
colnames(df_accuracy)[1] <- "subAct_metric"
colnames(df_accuracy)[3] <- "accuracy_ii"
```


```{r}
df_iiAll <- df_final
df_iiAcc <- df_accuracy
```


```{r}
write.csv(df_final, file="/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/energyOnly/df_final.csv")
write.csv(df_accuracy, file="/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/energyOnly/df_accuracy.csv")
```

```{r}
df_final <- dplyr::inner_join(df_iAll, df_iiAll, by = "subAct_metric")
df_accuracy <- dplyr::inner_join(df_iAcc, df_iiAcc, by = "subAct_metric")
```

```{r}
write.csv(df_final, file="/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/df_METRIC.csv")
write.csv(df_accuracy, file="/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/df_ACC.csv")
```


```{r}
df_METRIC <- read_csv("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/df_METRIC.csv")
df_ACC <- read_csv("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/df_ACC.csv")
```

```{r}
pairs(df_METRIC[,2:7], pch = 19)
```

```{r}
scatter_precision <- ggplot(data=df_METRIC, aes(precision_i, precision_ii, colour = metric)) +
  stat_smooth(method = "lm", col = "black", size = 0.5) +
  geom_point() + theme_grey() + scale_color_jco() + #scale_color_brewer(palette ="Dark2") +
  theme(legend.title = element_blank()) +
  annotate("text", x = 0.6, y = 0.85, label = "R Squared") + 
  annotate("text", x = 0.6, y = 0.8, label = format(summary(lm(precision_ii ~ precision_i, data = df_METRIC))$r.squared, digits = 4))
scatter_precision
```


```{r}
scatter_recall <- ggplot(data=df_METRIC, aes(recall_i, recall_ii, colour = metric)) +
  stat_smooth(method = "lm", col = "black", size = 0.5) +
  geom_point() + theme_grey() + scale_color_jco() +
  theme(legend.title = element_blank()) +
  annotate("text", x = 0.6, y = 0.85, label = "R Squared") + 
  annotate("text", x = 0.6, y = 0.8, label = format(summary(lm(recall_ii ~ recall_i, data = df_METRIC))$r.squared, digits = 4))
scatter_recall
```

```{r}
scatter_f1 <- ggplot(data=df_METRIC, aes(f1score_i, f1score_ii, colour = metric)) +
  stat_smooth(method = "lm", col = "dodgerblue", size = 0.5) +
  geom_point() + theme_grey() + scale_color_jco() +
  theme(legend.title = element_blank()) +
  annotate("text", x = 0.6, y = 0.85, label = "R Squared") + 
  annotate("text", x = 0.6, y = 0.8, label = format(summary(lm(f1score_ii ~ f1score_i, data = df_METRIC))$r.squared, digits = 4))
scatter_f1
```

```{r}
scatter_acc <- ggplot(data=df_ACC, aes(accuracy_i, accuracy_ii, colour = metric)) +
  stat_smooth(method = "lm", col = "black", size = 0.5) +
  geom_point() + theme_grey() + scale_color_aaas() +
  theme(legend.title = element_blank()) +
  annotate("text", x = 0.925, y = 0.975, label = "R Squared") + 
  annotate("text", x = 0.925, y = 0.925, label = format(summary(lm(accuracy_ii ~ accuracy_i, data = df_ACC))$r.squared, digits = 4))
scatter_acc
```

```{r fig.width=10, fig.height=8}
plot_grid(scatter_precision, scatter_recall, 
          scatter_f1, scatter_acc, labels = "AUTO", label_size = 8, nrow = 2,  rel_widths = c(1, 1, 1,1))
ggsave("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/images/facets2.png", 
       plot = last_plot(), device = png(), 
       scale = 1.5, width = 18, height = 13, units = c("cm"), dpi = 300)
```



```{r message=FALSE, warning=FALSE}
featPlots <- list()
for(i in 1:nrow(best_feats)) {
  filePath <- paste("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/", best_feats[[i,1]], sep = "")
  df <- read_csv(filePath)
  f <- ggplot(df, aes(reorder(feature, score), score)) + geom_bar(stat="identity")
  f <- f + coord_flip() + theme_gray()
  f <- f + labs(x = "Feature", y = "Importance") + 
    theme(text = element_text(size=8), 
        legend.title = element_blank(),
        axis.title.y=element_blank(),
        legend.position = c(0.9,0.12),
        legend.background = element_rect(fill=alpha('white', 0.5)),
        legend.key.size = unit(5, "mm"))
  list(i = i)
  featPlots[[i]] <- f
}
```

```{r}
#featPlots[[19]]
```

```{r message=FALSE, warning=FALSE}
dtPlots <- list()
for(i in 1:nrow(dt)) {
  filePath <- paste("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/", dt[[i,1]], sep = "")
  df <- read_csv(filePath)
  d <- ggplot(df, aes(max_depth, test_score, group = criterion, color = criterion))
  d <- d + geom_line(size=0.5) + geom_point(size = 0.5) + scale_colour_startrek() + theme_grey()
  d <- d + labs(x = "Maximum Depth", y = "Mean CV Score") +
  theme(text = element_text(size=8), 
        legend.title = element_blank(),
        legend.position = c(0.5,0.125),
        legend.background = element_rect(fill=alpha('white', 0.0)),
        legend.key.size = unit(2.5, "mm"))
  list(i = i)
  dtPlots[[i]] <- d
}
#dtPlots[[19]]
```

```{r message=FALSE, warning=FALSE}
rocPlots <- list()
for(i in 1:nrow(roc)) {
  filePath <- paste("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/", roc[[i,1]], sep = "")
  df <- read_csv(filePath)
  r <- ggplot(df, aes(fpr, tpr))
  r <- r + geom_line(size=0.5, colour="dodgerblue2") + geom_point(size = 0.5, colour="dodgerblue2") + theme_grey()
  r <- r + labs(x = "False Positive Rate (FPR)", y = "True Positive Rate (TPR)") + 
    scale_y_continuous(limits=c(0,1), expand = c(0, 0.01)) +
    scale_x_continuous(limits=c(0,1), expand = c(0, 0.01)) +
    theme(text = element_text(size=8))
  r <- r + geom_segment(aes(x = 0, y = 0, xend = 1, yend = 1))
  list(i = i)
  rocPlots[[i]] <- r
}
```

```{r}
rocPlots[[19]]
```

```{r}
nameVector <- gsub("_roc.csv", "_allFeatures.png", roc$X1)
```

```{r fig.width=10, fig.height=2.75}
for(i in 1:21) {
  filePath <- paste("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/", nameVector[i], sep = "")
  plot <- plot_grid(featPlots[[i]], dtPlots[[i]], rocPlots[[i]], labels = "AUTO", label_size = 8, nrow = 1,  rel_widths = c(1, 1, 1))
  plot
  ggsave(filePath, plot = last_plot(), device = png(), 
         scale = 1.5, width = 18, height = 4.5, units = c("cm"), dpi = 300)
  }
```


```{r}
nameVector
```











```{r}
library(readr)
files <- read_csv('/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/energyOnly/files.csv', 
    col_names = FALSE)
```

```{r}
best_feats <- dplyr::filter(files, grepl("best_feats", X1))
dt <- dplyr::filter(files, grepl("_dt", X1))
roc <- dplyr::filter(files, grepl("_roc", X1))
report <- dplyr::filter(files, grepl("_rep", X1))
confusion <- dplyr::filter(files, grepl("confusion", X1))
```

```{r message=FALSE, warning=FALSE}
featPlots <- list()
for(i in 1:nrow(best_feats)) {
  filePath <- paste("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/energyOnly/", best_feats[[i,1]], sep = "")
  df <- read_csv(filePath)
  f <- ggplot(df, aes(reorder(feature, score), score)) + geom_bar(stat="identity")
  f <- f + coord_flip() + theme_gray()
  f <- f + labs(x = "Feature", y = "Importance") +  
    theme(text = element_text(size=8), 
        legend.title = element_blank(),
        axis.title.y=element_blank(),
        legend.position = c(0.9,0.12),
        legend.background = element_rect(fill=alpha('white', 0.5)),
        legend.key.size = unit(5, "mm"))
  list(i = i)
  featPlots[[i]] <- f
}
```

```{r}
#featPlots[[19]]
```

```{r message=FALSE, warning=FALSE}
dtPlots <- list()
for(i in 1:nrow(dt)) {
  filePath <- paste("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/energyOnly/", dt[[i,1]], sep = "")
  df <- read_csv(filePath)
  d <- ggplot(df, aes(max_depth, test_score, group = criterion, color = criterion))
  d <- d + geom_line(size=0.5) + geom_point(size = 0.5) + scale_colour_startrek() + theme_grey()
  d <- d + labs(x = "Maximum Depth", y = "Mean CV Score") +
  theme(text = element_text(size=8), 
        legend.title = element_blank(),
        legend.position = c(0.5,0.125),
        legend.background = element_rect(fill=alpha('white', 0.0)),
        legend.key.size = unit(2.5, "mm"))
  list(i = i)
  dtPlots[[i]] <- d
}
```

```{r}
#dtPlots[[19]]
```


```{r message=FALSE, warning=FALSE}
rocPlots <- list()
for(i in 1:nrow(roc)) {
  filePath <- paste("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/energyOnly/", roc[[i,1]], sep = "")
  df <- read_csv(filePath)
  r <- ggplot(df, aes(fpr, tpr))
  r <- r + geom_line(size=0.5, colour="dodgerblue2") + geom_point(size = 0.5, colour="dodgerblue2") + theme_grey()
  r <- r + labs(x = "False Positive Rate (FPR)", y = "True Positive Rate (TPR)") + 
    scale_y_continuous(limits=c(0,1), expand = c(0, 0.01)) +
    scale_x_continuous(limits=c(0,1), expand = c(0, 0.01)) +
    theme(text = element_text(size=8), 
          legend.title = element_blank(),
          legend.position = c(0.9,0.12),
          legend.background = element_rect(fill=alpha('white', 0.5)),
          legend.key.size = unit(5, "mm"))
  r <- r + geom_segment(aes(x = 0, y = 0, xend = 1, yend = 1))
  list(i = i)
  rocPlots[[i]] <- r
}
```

```{r}
rocPlots[[19]]
```

```{r}
nameVector <- gsub("_roc.csv", "_energyOnly.png", roc$X1)
```

```{r fig.width=10, fig.height=2.75}
for(i in 1:21) {
  filePath <- paste("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/energyOnly/", nameVector[i], sep = "")
  plot <- plot_grid(featPlots[[i]], dtPlots[[i]], rocPlots[[i]], labels = "AUTO", label_size = 8, nrow = 1,  rel_widths = c(1, 1, 1))
  plot
  ggsave(filePath, plot = last_plot(), device = png(), 
         scale = 1.5, width = 18, height = 4.5, units = c("cm"), dpi = 300)
  }
```


```{r}
plot_grid(featPlots[[1]], dtPlots[[1]], rocPlots[[1]], labels = c("A", "T", "C"), label_size = 8, nrow = 1,  rel_widths = c(1, 1, 1))
```

```{r}
nameVector
```






```{r}
feat <- read_csv('/Users/alistairgj/kitchen_refrigerator_best_feats.csv')
dt <- read_csv('/Users/alistairgj/kitchen_refrigerator_dt.csv')
roc <- read_csv('/Users/alistairgj/kitchen_refrigerator_roc.csv')
```

```{r}
f <- ggplot(feat, aes(reorder(feature, score), score)) + geom_bar(stat="identity")
f <- f + coord_flip() + theme_gray()
f <- f + labs(x = "Feature", y = "Score") +
  theme(text = element_text(size=8), 
        legend.title = element_blank(),
        axis.title.y=element_blank(),
        legend.position = c(0.9,0.12),
        legend.background = element_rect(fill=alpha('white', 0.5)),
        legend.key.size = unit(5, "mm"))
f
```


```{r}
d <- ggplot(dt, aes(max_depth, test_score, group = criterion, color = criterion))
d <- d + geom_line(size=0.5) + geom_point(size = 0.5) + scale_colour_startrek() + theme_grey()
d <- d + labs(x = "Depth", y = "Score") +
  theme(text = element_text(size=8), 
        legend.title = element_blank(),
        legend.position = "right",
        legend.background = element_rect(fill=alpha('white', 0.5)),
        legend.key.size = unit(5, "mm"))
d
```



```{r}
r <- ggplot(roc, aes(fpr, tpr))
r <- r + geom_line(size=0.5, colour="dodgerblue2") + geom_point(size = 0.5, colour="dodgerblue2") + theme_grey()
r <- r + labs(x = "False Positive Rate", y = "True Positive Rate (Recall)") + 
  scale_y_continuous(limits=c(0,1), expand = c(0, 0.01)) +
  scale_x_continuous(limits=c(0,1), expand = c(0, 0.01)) +
  theme(text = element_text(size=8), 
        legend.title = element_blank(),
        legend.position = c(0.9,0.12),
        legend.background = element_rect(fill=alpha('white', 0.5)),
        legend.key.size = unit(5, "mm"))
r <- r + geom_segment(aes(x = 0, y = 0, xend = 1, yend = 1))
r
```



```{r fig.width=10, fig.height=2.75}
plot <- plot_grid(f, d, r, labels = "AUTO", label_size = 8, nrow = 1,  rel_widths = c(1, 1, 1))
plot
##ggsave("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/images/MLtest.png", 
##       plot = last_plot(), device = png(), 
#       scale = 1.5, width = 18, height = 4.5, units = c("cm"), dpi = 300)
```


```{r fig.width=10, fig.height=2}
subActNum = unique(dsPRE$subActNum)

strip_plot <- function(ds, i) {
  ds_filtered <- ds %>% filter(subActNum == i)
  d <- ggplot(ds_filtered, aes(durationSec, DAY))
  d <- d + geom_bin2d() + scale_y_discrete(limits=c('Sun', 'Sat', 'Fri', 'Thu', 'Wed', 'Tue', 'Mon')) +
    scale_x_continuous(expand = c(0.025, 0.025)) +
    scale_fill_viridis(breaks = function(x) unique(floor(pretty(seq(0, (max(x) + 1) * 1.1)))), direction = - 1) +
    theme_grey() +
    theme(legend.position = "none", axis.title.y=element_blank(), text = element_text(size=7),
          axis.text.x = element_text(size = 6, angle = 0)) + 
    labs(x = "Duration (Seconds)")

  e <- ggplot(ds_filtered, aes(HOUR, DAY))
  e <- e + geom_bin2d() + 
    scale_y_discrete(limits=c('Sun', 'Sat', 'Fri', 'Thu', 'Wed', 'Tue', 'Mon')) +
    scale_x_discrete(limits=c('4','5','6','7','8','9','10','11','12','13','14','15',
                              '16','17','18','19','20','21','22','23','0','1'), 
                     breaks=c('4', '5', '6','7','8','9','10','11','12','13','14','15',
                              '16','17','18','19','20','21','22','23','0','1'), expand = c(0.025, 0.025)) +
    scale_fill_viridis(breaks = function(x) unique(floor(pretty(seq(0, (max(x) + 1) * 1.1)))), direction = - 1) +
    theme_grey() +
    theme(legend.position = "right", axis.title.y=element_blank(), 
          text = element_text(size=7),
          axis.text.x = element_text(size = 6, angle = 0),
          legend.key.size = unit(1,"line")) + labs(x = "Hour of Day")
  
  f <- ggplot(ds_filtered, aes(x = DAY, y = durationSec, fill = DAY))
  f <- f + geom_boxplot() + coord_flip() +
    scale_x_discrete(limits=c('Sun', 'Sat', 'Fri', 'Thu', 'Wed', 'Tue', 'Mon')) +
    scale_y_continuous(expand = c(0.025, 0.025)) +
    theme_grey() +
    theme(legend.position = "none", axis.title.y=element_blank(), text = element_text(size=7),
          axis.text.x = element_text(size = 6, angle = 0)) + 
    labs(x = NULL, y = "Duration (Seconds)")

  plot_row = plot_grid(f, d, e, labels = "AUTO", label_size = 6, nrow = 1,  rel_widths = c(1, 1, 1.2))
  plot_grid(plot_row, ncol = 1, rel_heights = c(0.1, 1))
  
}
```

```{r fig.width=10, fig.height=4}
#p1 <- strip_plot(dsPRE, 139) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
#p2 <- strip_plot(dsPOST, 139) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
#plot_grid(p1, p2,
#  nrow = 2,
#  label_size = 8,
#  align = "v"
#)
```









#### Bathroom Lightswitch (SubActNum 101)

```{r fig.width=10, fig.height=2}
strip_plot(dsPRE, 101) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

ggsave("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/images/subAct101.png", 
       plot = last_plot(), device = png(), 
       scale = 1.5, width = 18, height = 3, units = c("cm"), dpi = 300)
```


#### Bathroom Medicine Cabinet (SubActNum 57)

```{r fig.width=10, fig.height=4}
p1 <- strip_plot(dsPRE, 57) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
p2 <- strip_plot(dsPOST, 57) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
plot_grid(p1, p2,
  nrow = 2,
  label_size = 8,
  align = "v"
)

ggsave("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/images/subAct57.png", 
			plot = last_plot(), device = png(), 
      scale = 1.5, width = 18, height = 6, units = c("cm"), dpi = 300)
```



#### Study Drawer (SubActNum 82)

```{r fig.width=10, fig.height=4}
p1 <- strip_plot(dsPRE, 82) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
p2 <- strip_plot(dsPOST, 82) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
plot_grid(p1, p2,
  nrow = 2,
  label_size = 8,
  align = "v"
)

ggsave("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/images/subAct82.png", 
			plot = last_plot(), device = png(), 
      scale = 1.5, width = 18, height = 6, units = c("cm"), dpi = 300)
```


#### Kitchen Refrigerator (SubActNum 126)

```{r fig.width=10, fig.height=2}
strip_plot(dsPRE, 126) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

ggsave("/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/images/subAct126.png", 
       plot = last_plot(), device = png(), 
       scale = 1.5, width = 18, height = 3, units = c("cm"), dpi = 300)
```




```{r}
reports <- '/Users/alistairgj/Documents/GitHub/IoT_ResearchProject/IoT_November/intermediate_datasets/allFeatures/'
file_list <- list.files(path=reports, pattern="*_rep.csv")
```

```{r}
data.report <- do.call("rbind", lapply(file_list, 
                                       function(x) 
                                         cbind(read.csv(paste(reports, x, sep='')))))
```


